# Hand-written config. ~/.local/state/noctalia/settings.toml is written by the
# settings GUI and overrides everything here.

[bar.default]
position = "left"
margin_ends = 0
widget_spacing = 6
capsule = true
start  = [ "group:apps" ]
center = [ "clock" ]
end    = [ "tray", "group:system" ]

[[bar.default.capsule_group]]
id = "apps"
members = [ "launcher", "taskbar" ]

[[bar.default.capsule_group]]
id = "system"
members = [ "network", "bluetooth", "volume", "brightness", "notifications", "control-center" ]

[widget.taskbar]
show_active_indicator = false
group_by_workspace = true
group_single_icon_per_app = true
workspace_group_capsule = true
workspace_group_content = "icons"
show_workspace_label = true
workspace_label_placement = "inside"
hide_empty_workspaces = false
show_window_title = false

[widget.clock]
vertical_format = "%H%n%M%n—%n%b%n%d"

[widget.tray]
drawer = true

[widget.network]
show_label = false

[widget.volume]
show_label = false

[shell]
polkit_agent = true
settings_show_advanced = false
font_family = "Adwaita Sans"
telemetry_enabled = false
external_ip_enabled = false

[shell.greeter_sync]
privilege_command = "run0 --setenv=PKEXEC_UID=1000"

[shell.panel]
clipboard_placement = "attached"
open_near_click_control_center = true
polkit_placement = "attached"
session_placement = "floating"
session_position = "center"

[theme]
mode = "auto"
source = "wallpaper"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri", "qt", "btop", "starship" ]
enable_community_templates = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900.0

[nightlight]
enabled = true

[notification]
position = "bottom_left"

[calendar]
enabled = true

[wallpaper]
directory = "/home/user/Pictures/Wallpapers"

[wallpaper.default]
path = "/home/user/Pictures/Wallpapers/26-05-05 09-37-10 2696.jpg"
